// @generated by protobuf-ts 2.8.2 with parameter long_type_string
// @generated from protobuf file "proto/OptionOrder.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message OptionOrder
 */
export interface OptionOrder {
    /**
     * @generated from protobuf field: repeated OptionOrder.Body optionOrder = 1;
     */
    optionOrder: OptionOrder_Body[];
}
/**
 * @generated from protobuf message OptionOrder.Body
 */
export interface OptionOrder_Body {
    /**
     * @generated from protobuf field: sint64 uid = 1;
     */
    uid: string;
    /**
     * @generated from protobuf field: sint64 orderId = 2;
     */
    orderId: string;
    /**
     * @generated from protobuf field: sint64 businessId = 3;
     */
    businessId: string;
    /**
     * @generated from protobuf field: string orderState = 4;
     */
    orderState: string;
    /**
     * @generated from protobuf field: sint64 optionId = 5;
     */
    optionId: string;
    /**
     * @generated from protobuf field: string symbol = 6;
     */
    symbol: string;
    /**
     * @generated from protobuf field: int32 profitable = 7;
     */
    profitable: number;
    /**
     * @generated from protobuf field: string profitValue = 8;
     */
    profitValue: string;
    /**
     * @generated from protobuf field: string coinSymbol = 9;
     */
    coinSymbol: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class OptionOrder$Type extends MessageType<OptionOrder> {
    constructor() {
        super("OptionOrder", [
            { no: 1, name: "optionOrder", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => OptionOrder_Body }
        ]);
    }
    create(value?: PartialMessage<OptionOrder>): OptionOrder {
        const message = { optionOrder: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<OptionOrder>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OptionOrder): OptionOrder {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated OptionOrder.Body optionOrder */ 1:
                    message.optionOrder.push(OptionOrder_Body.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OptionOrder, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated OptionOrder.Body optionOrder = 1; */
        for (let i = 0; i < message.optionOrder.length; i++)
            OptionOrder_Body.internalBinaryWrite(message.optionOrder[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message OptionOrder
 */
export const OptionOrder = new OptionOrder$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OptionOrder_Body$Type extends MessageType<OptionOrder_Body> {
    constructor() {
        super("OptionOrder.Body", [
            { no: 1, name: "uid", kind: "scalar", T: 18 /*ScalarType.SINT64*/ },
            { no: 2, name: "orderId", kind: "scalar", T: 18 /*ScalarType.SINT64*/ },
            { no: 3, name: "businessId", kind: "scalar", T: 18 /*ScalarType.SINT64*/ },
            { no: 4, name: "orderState", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "optionId", kind: "scalar", T: 18 /*ScalarType.SINT64*/ },
            { no: 6, name: "symbol", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "profitable", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "profitValue", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "coinSymbol", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<OptionOrder_Body>): OptionOrder_Body {
        const message = { uid: "0", orderId: "0", businessId: "0", orderState: "", optionId: "0", symbol: "", profitable: 0, profitValue: "", coinSymbol: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<OptionOrder_Body>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OptionOrder_Body): OptionOrder_Body {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* sint64 uid */ 1:
                    message.uid = reader.sint64().toString();
                    break;
                case /* sint64 orderId */ 2:
                    message.orderId = reader.sint64().toString();
                    break;
                case /* sint64 businessId */ 3:
                    message.businessId = reader.sint64().toString();
                    break;
                case /* string orderState */ 4:
                    message.orderState = reader.string();
                    break;
                case /* sint64 optionId */ 5:
                    message.optionId = reader.sint64().toString();
                    break;
                case /* string symbol */ 6:
                    message.symbol = reader.string();
                    break;
                case /* int32 profitable */ 7:
                    message.profitable = reader.int32();
                    break;
                case /* string profitValue */ 8:
                    message.profitValue = reader.string();
                    break;
                case /* string coinSymbol */ 9:
                    message.coinSymbol = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OptionOrder_Body, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* sint64 uid = 1; */
        if (message.uid !== "0")
            writer.tag(1, WireType.Varint).sint64(message.uid);
        /* sint64 orderId = 2; */
        if (message.orderId !== "0")
            writer.tag(2, WireType.Varint).sint64(message.orderId);
        /* sint64 businessId = 3; */
        if (message.businessId !== "0")
            writer.tag(3, WireType.Varint).sint64(message.businessId);
        /* string orderState = 4; */
        if (message.orderState !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.orderState);
        /* sint64 optionId = 5; */
        if (message.optionId !== "0")
            writer.tag(5, WireType.Varint).sint64(message.optionId);
        /* string symbol = 6; */
        if (message.symbol !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.symbol);
        /* int32 profitable = 7; */
        if (message.profitable !== 0)
            writer.tag(7, WireType.Varint).int32(message.profitable);
        /* string profitValue = 8; */
        if (message.profitValue !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.profitValue);
        /* string coinSymbol = 9; */
        if (message.coinSymbol !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.coinSymbol);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message OptionOrder.Body
 */
export const OptionOrder_Body = new OptionOrder_Body$Type();
